apiVersion: v1
entries:
  webapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-07-19T14:51:26.227761902Z"
    description: A Helm chart for Kubernetes
    digest: 49be2b18653fbb41dfe9d1c5b76985ec211c9f42bdf8959885448d0893752cc3
    name: webapp
    type: application
    urls:
    - https://github.com/Soundtech89/homelab-helm-repo.git/webapp-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-19T14:51:26.227229817Z"
